version: "3.9"

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: backend-bookstore
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/backend-bookstore
      JWT_SECRET: rahasia123
      PORT: 3000
    volumes:
      - .:/app
    command: sh -c "npx prisma db push && npx prisma db seed && npm run dev"

volumes:
  pgdata:
